### ISSUE TITLE
Black screen on Steam Deck

### ISSUE THREAD

**Issue by Mikethemlgdeck** [HarbourMasters/retro#66]
When starting the app image there is only a black screen and nothing else shows up.

**Comment by ComradeClaritux** [comment]
I also have this issue on Nobara (Fedora) Linux 40. Version 1.2 works fine
Console output:
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Cannot create file, path = 'latest.log' (OS Error: Read-only file system, errno = 30)
#0      _File.throwIfError (dart:io/file_impl.dart:675)
#1      _File.createSync (dart:io/file_impl.dart:306)
#2      main (package:retro/main.dart:35)
#3      _runMain.<anonymous closure> (dart:ui/hooks.dart:301)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
`

**Comment by SeongGino** [comment]
Same issue on Arch, unfortunately.

**Comment by XDM-Inc** [comment]
same here on fedora 41 desktop. even the windows version when ran on linux is the same. might be some kind of Flutter api setup needed but i dont see anything in the read me about it

**Comment by Mario-119** [comment]
Same issue here on SteamOS 3.7

**Comment by sabre230** [comment]
Same issue, Ubuntu 24.04.1 LTS

**Comment by StardustSauce** [comment]
Confirming that this is a regression that occurs only in the newest version, 0.2.0. Reverting to 0.1.2 causes no issue. I don't have experience with Flutter and can't confirm if it's present when built from source.

**Comment by XDM-Inc** [comment]
confirmation, the downgraded v12 DOES work

**Comment by DaemionJ** [comment]
Same on Mint. Though reverting to 0.1.2 wont let me open the app.
